apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-metrics-exporter
  namespace: custom-metric
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-metrics-exporter
  template:
    metadata:
      labels:
        app: my-metrics-exporter
    spec:
      containers:
      - image: ahmedbham.azurecr.io/custom-metric
        name: my-metrics-exporter
        ports:
        - containerPort: 6443
      

---

apiVersion: v1
kind: Service
metadata:
  name: my-metrics-exporter
  namespace: custom-metric
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 6443 
  selector:
    app: my-metrics-exporter