apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  minReplicas: 1
  maxReplicas: 10
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
      - type: Pods
        value: 1
        periodSeconds: 20
  metrics:
  - type: Object
    object:
      metric:
        name: instance
      describedObject:
        apiVersion: /v1beta1
        kind: Service
        name: my-metrics-exporter
        namespace: custom-metric
      target:
        type: Value
        value: 5

