apiVersion: v1
kind: Secret
metadata:
  name: batch-processor
  namespace: default
data:
  SERVICE_BUS: RW5kcG9pbnQ9c2I6Ly9zZXJ2aWNlLWJ1cy1uYW1lc3BhY2UtZGFwci5zZXJ2aWNlYnVzLndpbmRvd3MubmV0LztTaGFyZWRBY2Nlc3NLZXlOYW1lPWtlZGFydWxlO1NoYXJlZEFjY2Vzc0tleT05TXc0RmtHbENkRnJRR1JyaElhL2FVbDdaVnBFTkVPbGpSaGUzVUF2dnpvPTtFbnRpdHlQYXRoPWJhdGNocmVjZWl2ZWQ=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: batch-processor
  namespace: default
  labels:
    app: batch-processor
spec:
  selector:
    matchLabels:
      app: batch-processor
  template:
    metadata:
      labels:
        app: batch-processor
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "batch-processor"
        dapr.io/app-port: "3100"
        dapr.io/log-level: "debug"
        dapr.io/config: "tracing"
    spec:
      containers:
      - name: batch-processor
        image: dapr1batch.azurecr.io/batch-processor:v1
        ports:
        - containerPort: 3100
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: batch-processor
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: batch-processor-scaler
  namespace: keda
  labels:
    deploymentName: batch-processor
spec:
  scaleTargetRef:
    name: batch-processor
  minReplicaCount: 1 # Change to define how many minimum replicas you want
  cooldownPeriod:  60
  # maxReplicaCount: 5
  triggers:
  - type: azure-servicebus
    metadata:
      name: mySbMsg
      type: serviceBusTrigger
      direction: in
      topicName: batchreceived
      subscriptionName: batch-processor
      connection: SERVICE_BUS
      queueLength: '5'