apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: messagebus
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
  - name: connectionString
    value: "Endpoint=sb://service-bus-namespace-dapr.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=x0HJgf5enslQZnZ+2KBDoGvBhsaa584Ca+oRR0AKnoc=" # Required.
  - name: maxActiveMessages
    value: "1"
  - name: lockRenewalInSec
    value: "0"
  - name: maxDeliveryCount
    value: "10"