apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: outputqueue
  namespace: default
spec:
  metadata:
  - name: storageAccount
    value: dapr1batch
  - name: storageAccessKey
    secretKeyRef:
      name: output-queue-secret
      key: connectionString
  - name: queue
    value: dapr-output-queue
  - name: ttlInSeconds
    value: "60"
  - name: decodeBase64
    value: "false"
  type: bindings.azure.storagequeues
  version: v1
