apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: batchqueue
  # namespace: <NAMESPACE>
spec:
  type: bindings.azure.storagequeues
  version: v1
  metadata:
  - name: storageAccount
    value: "dapr1batch"
  - name: storageAccessKey
    value: "xxx"
  - name: queue
    value: "dapr-batch-queue"
  - name: ttlInSeconds
    value: "60"
  - name: decodeBase64
    value: "true"
